env:
  browser: true
  es6: true
extends: ["react-app", "eslint:recommended"]
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins: ["react", "jsx-a11y"]
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-useless-computed-key: "off"
